development:
  adapter: oracle_enhanced
  host: localhost
  port: 1521
  database: xe
  username: nacho
  password: nacho
  
test:
  adapter: oracle_enhanced
  host: localhost
  port: 1521
  database: xe
  username: nacho
  password: nacho
  
production:
  adapter: oracle_enhanced
  host: localhost
  port: 1521
  database: xe
  username: nacho
  password: nacho
